name: Sentiment Analysis with LLM Service
on:
  push:
    paths-ignore:
      - '**/*.ipynb'
      - 'README.md'
jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker-compose.test.yaml up --build